#!/usr/bin/python3
# -*-python-*-

import os
import sys

def make_link(f, t, symlink):
    if os.path.exists(f):
        tmp = input(t + ' exists already, do you want to replace it? [Y/n]: ')
        if tmp == '' or tmp == 'Y' or tmp == 'y':
            os.remove(t)
        else:
            return
    if symlink:
        os.link(f, t)
    else:
        os.symlink(f, t)

work_dir = os.getcwd()
home_folder = os.getenv("HOME")

print('Dir with the stuff to link with: ... ' + work_dir)
print('Home folder location: .............. ' + home_folder + '\n')

tmp = input('Are this correct locations [Y/n]? ')
if tmp == '' or tmp == 'Y' or tmp == 'y':
    os.chdir(home_folder)
    print('Changed working dir to: ' + home_folder)
    make_link(work_dir + '/emacs', '.emacs', False)
    make_link(work_dir + '/bashrc', '.bashrc', False)
    make_link(work_dir + '/muttrc', '.muttrc', False)
    make_link(work_dir + '/Xresources', '.Xresources', False)
    make_link(work_dir + '/zshrc', '.zshrc', False)
    make_link(work_dir + '/conkyrc', '.conkyrc', False)
    make_link(work_dir + '/i3', '.i3', False)
    make_link(work_dir + '/zsh', '.zsh', False)
    print('Created all symlinks.')
else:
    print('Selected no.')
