#!/usr/bin/python3
# -*-python-*-

import os
import sys

def make_link(f, t):
    if os.path.exists(home_folder + '/' + t):
        tmp = input(t + ' exists already, do you want to replace it? [Y/n]: ')
        if tmp == '' or tmp == 'Y' or tmp == 'y':
            os.remove(t)
            os.symlink(f, t)
    else:
        os.symlink(f, t)

work_dir = os.getcwd() + '/config_files'
home_folder = os.getenv("HOME")

print('Dir with the stuff to link with: ... ' + work_dir)
print('Home folder location: .............. ' + home_folder + '\n')

tmp = input('Are this correct locations [Y/n]? ')

if tmp == '' or tmp == 'Y' or tmp == 'y':
    os.chdir(home_folder)
    print('Changed working dir to: ' + home_folder)
    for f in os.listdir(work_dir):
        make_link(work_dir + '/' + f, '.' + f)

    print('Created all symlinks.')
else:
    print('Selected no.')
