set clipboard=unnamedplus
syntax enable

set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

colorscheme molokai
let g:molokai_original = 0
set background=dark
set guioptions-=m
set guioptions-=T
set guioptions-=r
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/
set number
set nowrap
set ttyfast
set cursorline
set nocompatible
set nobackup
set nowritebackup
set ttimeoutlen=50
set laststatus=2
set cino+=(0

Bundle 'gmarik/vundle'

Bundle 'vim-scripts/glsl.vim'
Bundle 'wting/rust.vim'
Bundle 'vim-scripts/ag.vim'
Bundle 'bling/vim-airline'
Bundle 'tpope/vim-fugitive'
Bundle 'majutsushi/tagbar'
Bundle 'scrooloose/nerdtree'
Bundle 'junegunn/vim-easy-align'
Bundle 'Valloric/YouCompleteMe'
Bundle 'moll/vim-bbye'

filetype plugin indent on

nmap <F8> :TagbarToggle<CR>

let g:tagbar_type_rust = {
            \ 'ctagstype' : 'rust',
            \ 'kinds' : [
            \ 'f:function',
            \ 'T:types',
            \ 'm:types',
            \ 'm:modules',
            \ 'm:consts',
            \ 'm:traits',
            \ 'm:impls',
            \ 'M:macros'
            \ ]
            \ }

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

nmap ,d :Bdelete<CR>
