#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb .Xresources
export SDL_VIDEO_FULLSCREEN_HEAD=1
#exec xmonad
cmst &
qopenvpn &
dropboxd &
unclutter &

compton -r 12 -o 0.75 -C --vsync opengl --unredir-if-possible --backend glx &
redshift -l 59.86:17.65 &

setxkb se &
nitrogen --restore &

exec awesome
#exec startkde
#exec cinnamon-session
