set clipboard=unnamedplus
syntax enable

set background=dark
colorscheme solarized
set guioptions-=m
set guioptions-=T
set guioptions-=r
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/
set guifont:Dina:h10
set number
set nowrap

execute pathogen#infect()
filetype plugin indent on

nmap <F8> :TagbarToggle<CR>

let g:tagbar_type_rust = {
            \ 'ctagstype' : 'rust',
            \ 'kinds' : [
            \ 'f:function',
            \ 'T:types',
            \ 'm:types',
            \ 'm:modules',
            \ 'm:consts',
            \ 'm:traits',
            \ 'm:impls',
            \ 'M:macros'
            \ ]
            \ }

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
set ttimeoutlen=50
set laststatus=2

set cino+=(0
